---
heat_template_version: 2016-10-14

###########
parameters:

  image_jitsi:
    type: string
    constraints:
      - custom_constraint: glance.image
    default: openSUSE 15.1

  flavor_jitsi:
    type: string
    constraints:
      - custom_constraint: nova.flavor
    default: s2.large.4

  availability_zone:
    type: string
    default: eu-de-03

  public:
    type: string
    constraints:
      - custom_constraint: neutron.network
    default: admin_external_net

  jitsi_user:
    type: string

  jitsi_password:
    type: string

  public_url:
    type: string

  letsenc_mail:
    type: string
  
  letsenc_domain:
    type: string

##########
resources:

  #########
  # Generic
  #########

  key:
    type: OS::Nova::KeyPair
    properties:
      name: jitsi_key
      save_private_key: true

  jitsi_wait_handle:
    type: OS::Heat::WaitConditionHandle

  jitsi_wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: jitsi_wait_handle}
      timeout: 1200

  jitsi_boot_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        package_update: true
        package_upgrade: true
        packages:
          - docker
          - docker-compose
          - make
        write_files:
          - content: {get_file: cert.crt}
            path: /root/cert.crt
            permissions: 0644
          - content: {get_file: cert.key}
            path: /root/cert.key
            permissions: 0600
          - content:
              str_replace:
                params:
                  wc_notify: {get_attr: ['jitsi_wait_handle', 'curl_cli']}
                  jitsi_user: {get_param: jitsi_user}
                  jitsi_password: {get_param: jitsi_password}
                  public_url: {get_param: public_url}
                template: |
                  #!/usr/bin/env bash
                  export USER=root
                  export USERNAME=$USER
                  export HOME=/$USER
                  cd ~
                  systemctl stop SuSEfirewall2
                  sysctl -w net.ipv4.ip_forward=1
                  systemctl enable docker
                  systemctl restart docker
                  mkdir -p ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody,jicofo,jvb}
                  git clone https://github.com/jitsi/docker-jitsi-meet
                  cd docker-jitsi-meet
                  make
                  cp -p docker-compose.yml etherpad.yml ~
                  cp -p env.example ~/.env
                  cd ..
                  # This is only used internally
                  sed -i 's/passw0rd/p@33W0rd/g' .env
                  sed -i 's@^#PUBLIC_URL=.*$@PUBLIC_URL=public_url/@' .env
                  IP=$(ip addr show eth0 | grep 'inet ' | sed 's@^ *inet \([0-9\.]*\)/\([0-9]*\) .*$@\1@')
                  sed -i "s@^#DOCKER_HOST_ADDRESS=.*\$@DOCKER_HOST_ADDRESS=$IP@" .env
                  #sed -i 's/^#LETSENCRYPT_EMAIL=.*$/LETSENCRYPT_EMAIL=letsenc_mail/' .env
                  #sed -i 's@^#LETSENCRYPT_DOMAIN=.*$@LETSENCRYPT_DOMAIN=letsenc_domain@' .env
                  #sed -i 's@^#ETHERPAD_URL_BASE@ETHERPAD_URL_BASE@' .env
                  sed -i 's@^#ENABLE_AUTH@ENABLE_AUTH@' .env
                  sed -i 's@^#ENABLE_GUESTS@ENABLE_GUESTS@' .env
                  sed -i 's@^#AUTH_TYPE=@AUTH_TYPE=@' .env
                  #docker-compose -f ~/docker-compose.yml -f ~/etherpad.yml up -d
                  docker-compose -f ~/docker-compose.yml up -d
                  # Deploy SSL cert
                  openssl dhparam -out ~/.jitsi-meet-cfg/web/nginx/dhparams.pem 2048
                  # Comment out if you do not want to inject a pre-generated certificate
                  # Instead enable LETSENCRYPT above
                  cp -p cert.crt ~/.jitsi-meet-cfg/web/keys/cert.crt
                  cp -p cert.key ~/.jitsi-meet-cfg/web/keys/cert.key
                  # Deploy one user
                  docker exec root_prosody_1 prosodyctl --config /config/prosody.cfg.lua register jitsi_user meet.jitsi jitsi_password
                  docker restart root_web_1
                  # TODO: 
                  # Update DNS entry for garloff6.de
                  wc_notify --data-binary '{"status": "SUCCESS"}'

            path: /root/run.sh
            permissions: 0700
          - content: |
              #!/bin/bash
              export USER=root
              export USERNAME=$USER
              export HOME=/$USER
              cd ~
              #docker-compose -f ~/docker-compose.yml -f ~/etherpad.yml down
              docker-compose -f ~/docker-compose.yml down
            path: /root/down.sh
            permissions: 0750

        runcmd:
          - "systemctl enable docker"
          - "/root/run.sh"
        final_message: "The system is finally up, after $UPTIME seconds"


  #################
  # Security groups
  #################

  security_group_jitsi:
    type: OS::Neutron::SecurityGroup
    properties:
      name: jitsi
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 8443
          port_range_max: 8443
        - remote_ip_prefix: 0.0.0.0/0
          protocol: udp
          port_range_min: 10000
          port_range_max: 10010

  ############
  # Networks #
  ############

  net_jitsi:
    type: OS::Neutron::Net
    properties:
      name: jitsi

  subnet_jitsi:
    type: OS::Neutron::Subnet
    properties:
      network: {get_resource: net_jitsi}
      cidr: 192.168.10.0/24
      # OTC
      #dns_nameservers: [ 100.125.4.25, 9.9.9.9 ]
      dns_nameservers: [ 9.9.9.9, 8.8.8.8 ]
      allocation_pools:
        -
          start: 192.168.10.100
          end: 192.168.10.120

  ##########################
  # Network infrastructure #
  ##########################

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: {get_param: public}
        # OTC
        # enable_snat: true     

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: {get_resource: router}
      subnet: {get_resource: subnet_jitsi}

  ###########
  # Manager #
  ###########

  jitsi_port:
    type: OS::Neutron::Port
    properties:
      network_id: {get_resource: net_jitsi}
      fixed_ips:
        - ip_address: 192.168.10.99
      security_groups:
        - {get_resource: security_group_jitsi}

  jitsi_floating_ip:
    type: OS::Neutron::FloatingIP
    depends_on: router_interface
    properties:
      floating_network_id: {get_param: public}
      port_id: {get_resource: jitsi_port}

  jitsi_server:
    type: OS::Nova::Server
    properties:
      name: jitsi
      key_name: {get_resource: key}
      image: {get_param: image_jitsi}
      flavor: {get_param: flavor_jitsi}
      availability_zone: {get_param: availability_zone}
      user_data_format: SOFTWARE_CONFIG
      user_data: {get_resource: jitsi_boot_config}
      metadata:
        group: jitsi
      config_drive: true
      networks:
        - port: {get_resource: jitsi_port}

########
outputs:

  jitsi_address:
    value: {get_attr: [jitsi_floating_ip, floating_ip_address]}

  jitsi_address_internal:
    value: {get_attr: [jitsi_port, fixed_ips, 0, ip_address]}

  public_key:
    value: {get_attr: [key, public_key]}

  private_key:
    value: {get_attr: [key, private_key]}
